version: '3'

services:
  dev_db:
    image: postgres:12-alpine
    env_file: .env
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 5s
