version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # NOTE: We must expose these args to Dockerfile because they are used in next.config.js
      args:
        - DOMAIN=${DOMAIN}
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - ./public/uploads:/app/public/uploads
    ports:
      - 127.0.0.1:3000:3000
      # NOTE: In case, if you want to use ./ops/nginx.sh, uncomment this line:
      # - 3000:3000
    healthcheck:
      test:
        ['CMD-SHELL', 'curl http://app:3000/api/status | grep true > /dev/null']
      interval: 5s
      timeout: 5s

  db:
    image: postgres:12-alpine
    env_file: .env
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 5s
