name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      TZ: UTC
      PGTZ: UTC

    services:
      db:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test
        ports: ['5432:5432']
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Prepare .env
        run: cp .env.example .env.test

      - run: npm ci
      - run: make test
